- type: job
  id: NTClown
  name: job-name-nt-clown
  description: job-description-clown
  playTimeTracker: JobNTClown
  startingGear: ClownGear
  icon: "JobIconClown"
#  supervisors: job-supervisors-hop
  access:
  - NanotrasenService
  - NanotrasenCrew
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
      catchingFailDamage:
        types:
          Blunt: 1
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

#- type: startingGear
#  id: ClownGear
#  equipment:
#    mask: ClothingMaskClown
#    pocket1: BikeHorn
#    pocket2: ClownRecorder
#    id: ClownPDA
#    ears: ClothingHeadsetService
#  storage:
#    back:
#    - RubberStampClown
#    - CrayonRainbow

#- type: chameleonOutfit
#  id: ClownChameleonOutfit
#  job: Clown
#  equipment:
#    head: ClothingHeadHatXmasCrown
#    eyes: ClothingEyesGlassesCheapSunglasses
#    neck: ClothingHeadHatFlowerWreath
#    outerClothing: ClothingOuterClownPriest
#    gloves: ClothingHandsGlovesColorYellowBudget




- type: job
  id: SyndicateClown
  name: job-name-syndicate-clown
  description: job-description-clown
  playTimeTracker: JobSyndicateClown
  startingGear: ClownGear
  icon: "JobIconClown"
#  supervisors: job-supervisors-hop
  access:
  - SyndicateService
  - SyndicateCrew
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
      catchingFailDamage:
        types:
          Blunt: 1
    - type: SleepEmitSound
      snore: /Audio/Voice/Misc/silly_snore.ogg
      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

#- type: startingGear
#  id: ClownGear
#  equipment:
#    mask: ClothingMaskClown
#    pocket1: BikeHorn
#    pocket2: ClownRecorder
#    id: ClownPDA
#    ears: ClothingHeadsetService
#  storage:
#    back:
#    - RubberStampClown
#    - CrayonRainbow

#- type: chameleonOutfit
#  id: ClownChameleonOutfit
#  job: Clown
#  equipment:
#    head: ClothingHeadHatXmasCrown
#    eyes: ClothingEyesGlassesCheapSunglasses
#    neck: ClothingHeadHatFlowerWreath
#    outerClothing: ClothingOuterClownPriest
#    gloves: ClothingHandsGlovesColorYellowBudget
